#!/bin/bash

echo "🔧 GUÍA PARA CONFIGURAR VARIABLES DE ENTORNO EN VERCEL"
echo "============================================================"
echo ""
echo "📝 PASOS A SEGUIR:"
echo ""
echo "1. 🌐 Accede a Vercel:"
echo "   - Ve a: https://vercel.com"
echo "   - Inicia sesión en tu cuenta"
echo ""
echo "2. 🎯 Selecciona tu proyecto:"
echo "   - Busca y selecciona el proyecto: signa-jhk5"
echo "   - (O el proyecto que corresponda a https://signa-jhk5.vercel.app)"
echo ""
echo "3. ⚙️ Ve a configuración:"
echo "   - Haz clic en la pestaña 'Settings'"
echo "   - En el menú lateral, busca 'Environment Variables'"
echo ""
echo "4. ➕ Agregar variable de entorno:"
echo "   - Haz clic en 'Add New'"
echo "   - Name: NEXT_PUBLIC_API_URL"
echo "   - Value: https://heartfelt-insight-production-3a55.up.railway.app"
echo "   - Environments: Marca Production, Preview y Development"
echo "   - Haz clic en 'Save'"
echo ""
echo "5. 🚀 Redeployar:"
echo "   - Ve a la pestaña 'Deployments'"
echo "   - Encuentra el deployment más reciente"
echo "   - Haz clic en los 3 puntos (...) al lado derecho"
echo "   - Selecciona 'Redeploy'"
echo "   - Confirma el redeploy"
echo ""
echo "📋 INFORMACIÓN IMPORTANTE:"
echo "   Frontend URL: https://signa-jhk5.vercel.app"
echo "   Backend URL:  https://heartfelt-insight-production-3a55.up.railway.app"
echo ""
echo "⏱️ El redeploy toma aproximadamente 2-3 minutos"
echo ""
echo "✅ VERIFICACIÓN:"
echo "   Una vez completado, prueba crear/editar/eliminar marcas en:"
echo "   https://signa-jhk5.vercel.app"
echo ""
